### PR TITLE
Optimize gradle & Update dependencies & Add CI config

### PR DESCRIPTION
**Pull request by Goooler**
- Add `base.gradle` to simplify gradle config.
- Add github action CI config to publishToMavenLocal, and you may need to config the [signing info](https://github.com/vanniktech/gradle-maven-publish-plugin#signing) in enviroment variables.
- Move properties into `gradle.properties`.
- And more...

### CODE REVIEW

**Comment by RikkaW** [comment]
> Move properties into gradle.properties.

The reason I move it to `build.gradle` is I don't want an extra file for each module.

> Add base.gradle to simplify gradle config.

I want to do it in the root `build.gradle`.

```
subprojects {
    afterEvaluate {
```

Also, this pr changes too many files. It's better to separate them.

**Comment by Goooler** [comment]
1. I think we can keep the each `gradle.properties` for regular configs.
2. There are `base.gradle` & `kotlin.gradle` for modules import.
3. I tested in my local, it hard to separate them as too many changes, you can use rebase merge.

**Comment by Goooler** [comment]
I squashed commits to 12.

**Comment by RikkaW** [comment]
I don't want module every module has an extra `gradle.properties`.

**Comment by Goooler** [comment]
你也是够固执的，我没发现把 pom 信息都塞到一个文件里面去有什么好处.

**Comment by RikkaW** [comment]
那分开也没好处呀，写在 build.gradle 至少想改的时候方便点。
另外，看起来你的 pr 全都是这种改改 gradle，升级依赖这种不疼不痒的东西，**并且不顾别人项目的实际情况，加一堆自己习惯的东西**，大部分人没直接给你关了就算好的了 :)

**Comment by Goooler** [comment]
行，你开心就好

**Pull request closed without merging**
